### ISSUE TITLE
paramKeys and paramValues are not cleared in the for loop

### ISSUE THREAD

**Issue by arvindmorwal** [scottcorgan/pathetic#1]
in the main function's for loop. the value for the paramKeys and paramValues are not cleared in the iterations. So if you have multiple urls then it keeps on adding in the paramValues and paramKeys. Thus giving unwanted values.

Possible fix in the for loop: 
for(i; i < len; i += 1) {
//reset the values for paramKeys and paramValues from last iteration
      paramKeys = [];
      paramValues = [];

Thus clearing the values for each iteration for matching. I used redirects npm package that has the dependency on pathematics which has dependency on pathetic.

**Comment by scottcorgan** [comment]
Closed by https://github.com/scottcorgan/pathetic/commit/1a3dc278300edc29a7ed432406401fe24130ab68
